// mypages.js
// 2023-03-01: by jcr



exports.genFirstPage = function(lista, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>Home page</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>O que deseja consultar?</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Opção</th>
                </tr>

                <tr>
                    
                        <td>
                            <a href="http://localhost:7788/pessoas">
                                Lista de pessoas
                            </a>
                        </td>
                        <td>
                            <a href="http://localhost:7788/sexos">
                                Distribuição por sexo
                            </a>
                        </td>
                        <td>
                            <a href="http://localhost:7788/desportos">
                                Distribuição por desporto
                            </a>
                        </td>
                        <td>
                            <a href="http://localhost:7788/top10">
                                Top 10 profissões
                            </a>
                        </td>
                        
                </tr>
        `
    

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.genMainPage = function(lista, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7788/pessoas/${lista[i].id}">
                                ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}


exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>${pessoa.nome}</h1>
            </header>
    
        <div class="w3-container">
            `
    pagHTML += `
            
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.getDistSexPage = function(lista,data){
    const mapaSex = new Map();
    mapaSex.set("feminino",0)
    mapaSex.set("masculino",0)
    mapaSex.set("outro",0)
    
    for(let i=0; i<lista.length;i++){
        if(lista[i].sexo.toLowerCase() == "feminino"){
            let valor = mapaSex.get("feminino");
            valor+=1;
            mapaSex.set("feminino",valor);
        }else if(lista[i].sexo.toLowerCase() == "masculino"){
            let valor = mapaSex.get("masculino");
            valor+=1;
            mapaSex.set("masculino",valor);
        }else{
            let valor = mapaSex.get("outro");
            valor+=1;
            mapaSex.set("outro",valor);
        }
    }
    
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>Pessoas</title>
        <link rel="stylesheet" href="w3.css"/> 
        <style>
            footer {
                position: fixed;
                bottom: 0;
                width: 100%;
                height: 50px;
            }
        </style>
    </head>
    <body>
        
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Distribuição por sexo</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                  <th>Sexo</th>
                  <th>Nº pessoas</th>
                </tr>`
    
        pagHTML += `
                <tr>
                    <td>Feminino</td>
                    <td>
                        <a href="http://localhost:7788/sexs/feminino">
                        ${mapaSex.get("feminino")}
                        </a>
                    </td>
                </tr>
                <tr>
                <tr>
                    <td>Masculino</td>
                    <td>
                        <a href="http://localhost:7788/sexs/masculino">
                        ${mapaSex.get("masculino")}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>Outro</td>
                    <td>
                        <a href="http://localhost:7788/sexs/outro">
                        ${mapaSex.get("outro")}
                        </a>
                    </td>
                </tr>    
        `
    pagHTML+= `           
            </table>
        </div>
        <footer class="w3-container w3-teal">
            <h5>Generated by a97652-server: ${data}</h5>
        </footer>
        </div> 
    </body>
</html>
    `
return pagHTML
}

exports.getDistSportsPage = function(lista,data){
    const mapDesporto = new Map();
    for(let i=0; i<lista.length;i++){
        for(let j=0; j<lista[i].desportos.length;j++){
            if(mapDesporto.has((lista[i].desportos[j]))){
                let valor = mapDesporto.get((lista[i].desportos[j]));
                valor+=1;
                mapDesporto.set((lista[i].desportos[j]),valor);
            }else{
                mapDesporto.set((lista[i].desportos[j]),1);
            }
        }
    }
    
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>Pessoas</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Distribuição por desporto</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Desporto</th>
                    <th>Nº de praticantes</th>
                </tr>`
  

        //Ciclo for para ver as keys existentes
        for(let i=0; i<mapDesporto.size;i++){
            pagHTML+=`
                <tr>
                    <td>${(Array.from(mapDesporto.keys()))[i]}</td>
                    <td>
                        <a href="http://localhost:7788/sports/${(Array.from(mapDesporto.keys()))[i]}">
                        ${mapDesporto.get((Array.from(mapDesporto.keys()))[i])}
                        </a>
                    </td>
                </tr>`
        }

    pagHTML+= `           
            </table>
        </div>
        <footer class="w3-container w3-teal">
            <h5>Generated by a97652-server: ${data}</h5>
        </footer>
        </div> 
    </body>
</html>`
return pagHTML
}